import Head from "next/head";
import Image from "next/image";
import Gears from "../public/gears.webp";
import { AiFillTwitterCircle, AiFillInstagram } from "react-icons/ai";

export default function Home() {
  const links = [
    {
      id: 1,
      title: "About Us",
    },
    {
      id: 2,
      title: "Services",
    },
    {
      id: 3,
      title: "Spares",
    },
    {
      id: 4,
      title: "Contact",
    },
  ];
  const Services = [
    {
      id: 1,
      title: "INTERIM CAR SERVICE",
      type: "Small Scale Maintenance",
      description: [
        {
          id: 1,
          title: "Oil Change and Filter Replacement",
        },
        {
          id: 2,
          title: "Serpentine Belt Inspection",
        },
        {
          id: 3,
          title: "Wiper Blade Inspection",
        },
        {
          id: 4,
          title: "Tire Pressure Checks",
        },
      ],
    },
    {
      id: 2,
      title: "FULL SERVICE CAR INTERVALS",
      type: "Full Service",
      description: [
        {
          id: 1,
          title: "Engine Air Filter",
        },
        {
          id: 2,
          title: "Cabin Air Filter",
        },
        {
          id: 3,
          title: "Brake Pads",
        },
        {
          id: 4,
          title: "Coolant",
        },
        {
          id: 3,
          title: "Belts and hoses",
        },
      ],
    },
    {
      id: 3,
      title: "MAJOR CAR SERVICE",
      type: "Combined annual checks",
      description: [
        {
          id: 1,
          title: "Brake Fluid Exchange",
        },
        {
          id: 2,
          title: "Spark Plug Replacement",
        },
        {
          id: 3,
          title: "Transmission and Fluid Inspection",
        },
        {
          id: 4,
          title: "Timing Belt Replacement",
        },
        {
          id: 5,
          title: "Battery Setting",
        },
        {
          id: 6,
          title: "Tire Replacement",
        },
      ],
    },
  ];
  return (
    <>
      <Head>
        <title>Firebeats Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-full bg-teal-200">
        <section className="bg-teal-300 flex justify-between px-5 py-5">
          <div className="text-2xl font-bold pt-1 cursor-pointer">
            Olosko Auto Spares
          </div>
          <div className="flex gap-4">
            {links.map(({ id, title }) => {
              return (
                <button
                  key={id}
                  className="py-2 px-4 hover:font-semibold rounded-full bg-[#3498db]"
                >
                  {title}
                </button>
              );
            })}
          </div>
        </section>
        <section className="px-10 py-5 w-full h-[500px] flex max-w-4xl mx-auto">
          <div className="basis-1/2 mt-56">
            <span className="mb-2 text-3xl font-semibold">
              Welcome to Olosko Spares
            </span>
            <br />
            <span className="leading-4">
              for all your motoring service needs
            </span>
            <button className="mt-4 rounded-full px-4 py-2 hover:font-semibold bg-[#3498db] ">
              Get Started
            </button>
          </div>
          <div className="basis-1/2 mt-56">
            <div className="w-full h-full object-cover">
              <Image src={Gears} alt="Logo here" contain />
            </div>
          </div>
        </section>
        <section className="max-w-7xl mx-auto py-5 px-10">
          <div className="grid place-items-center">
            <h3 className="font-semibold text-3xl py-2">About Us</h3>
            <h5 className="font-medium text-xl py-1">Your Premium Autoshop</h5>
            <p className="leading-8 px-2 py-2">
              We at Olosko Auto Shop are dealers in various spares for a number
              of vehicle brands, we have a long history of providing genuine and
              affordable prices to all our customers. We are reliable and
              command a large customer base.
            </p>
            <p className="leading-8 px-2 py-1">
              The company started back in 2005 as the result of three
              Ex-Marshall Kenya mechanics quit to venture into entrepreneurship,
              Over the years the small startup has emerged and provided services
              to different customers from Nairobi. In 2010, the company ventured
              into the spare parts dealing businesses having secured a reliable
              source from Asia and Europe as most of the brands in the country
              originate from such areas of the world.
            </p>
          </div>
        </section>
        <section className="grid place-items-center">
          <h2 className="font-semibold text-3xl py-2">Services</h2>
        </section>
        <section className="px-10 py-5 max-w-6xl mx-auto gap-5 grid place-items-center grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
          {Services.map(({ id, title, type, description }) => {
            return (
              <div
                key={id}
                className="rounded-xl shadow-xl w-[330px]  h-[550px] flex flex-col items-center justify-center"
              >
                <h3 className="font-semibold text-xl">{title}</h3>
                <h4 className="font-medium text-base">{type}</h4>
                {description.map(({ id, title }) => {
                  return (
                    <p key={id} className="flex flex-col py-4">
                      <span>{title}</span>
                    </p>
                  );
                })}

                <button className="rounded-full font-medium py-2 px-4 bg-blue-500">
                  Get Quote
                </button>
              </div>
            );
          })}
        </section>
        {/*<section className="">Spares</section>*/}
        <section className="px-10 py-5 grid place-items-center">
          <div className="w-[300px] h-fit md:w-[600px]">
            <form
              method="POST"
              className="flex flex-col gap-4 shadow-xl rounded-xl py-4 px-4"
            >
              <h2 className="grid place-items-center font-semibold text-2xl">
                Fill in the form to get in touch
              </h2>
              <input
                className="rounded-lg px-6 py-3"
                type="text"
                name="name"
                placeholder="Enter Your Name..."
              />
              <input
                className="rounded-lg px-6 py-3"
                type="email"
                name="email"
                placeholder="Enter Your Email.."
              />
              <input
                className="rounded-lg px-6 py-3"
                type="phone"
                name="phone"
                placeholder="Enter Your Phone Number.."
              />
              <textarea
                className="rounded-lg px-6 py-3"
                rows={10}
                name="message"
                placeholder="Enter Your Message"
              />
              <button className="rounded-lg px-6 py-3 bg-blue-300">
                Submit
              </button>
            </form>
          </div>
        </section>
        <section className="w-full bg-blue-200 grid place-items-center py-5">
          <div className="h-fit">
            <div className="font-semibold text-base">
              Olosko Auto Spares &copy; 2023
            </div>
            <div className="flex gap-5 items-center justify-center">
              <AiFillTwitterCircle size={30} />
              <AiFillInstagram size={30} />
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
